@startuml
title WarmHouse Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

Person(user, "Пользователь", "Просматривает состояние, управляет, регистрирует датчики")
Person(administrator, "Администратор", "Управляет подключением пользователей, устройств, сетвой безопасностью и телеметрией")
System(WarmHouseSystem, "Умный дом", "Управление датчиками, мониторинг данных с датчиков, регистрация датчиков")

Person(user, "Пользователь", "Просматривает состояние, управляет, регистрирует датчики")
Person(administrator, "Администратор", "Управляет подключением пользователей")


Container(WebApp, "Web-приложение", "Go", "Интерфейс управление умным домом")

Rel(user, WebApp, "Управление умным домом")
Rel(administrator, WebApp,"Управляет подключениями и разрешениями пользователей")


Boundary(WarmHouseSystem, "Умный дом") {
 
 Boundary(ScalingDomain, "Домен масштабирования") {
    Container(APIGW, "API-Gateway/Reverse proxy MQTT", "NGinx", "Масштабирование, балансировка нагрузки, шифрование трафика, проксирование и аутентификация MQTT устройств")
 
    Container(UserAuth, "Идентификация и аутентификация пользователей", "Go", "Регистрация, аутентификация пользователей и получение прав доступа к ресурсам")
    ContainerDb(UserAuthDB, "Database", "PostgreSQL", "Хранит данные и полномочия пользователей")
    Container(DeviceAuth, "Регистрация устройств", "Go", "Идентификация и аутентификация устройств")
    ContainerDb(DeviceAuthDB, "База зарегистрированных устройств", "PostgreSQL", "Хранит данные о подключённых устройствах")

    Rel(APIGW, UserAuth,"Аутентификация пользователей [REST]")
    Rel(APIGW, DeviceAuth,"Чтение/запись данных о пользователях")
    Rel(UserAuth, UserAuthDB,"Регистрация устройств[REST]")
    Rel(DeviceAuth, DeviceAuthDB,"Регистрация/изменение устройств")

  }

  Boundary(MonitoringDomain, "Домен мониторинга данных с устройств") {
  
    Container(TemprSensor, "Мониторинг температуры", "Go", "Предоставляет данные температуры")
    ContainerDb(TemprSensorDB, "База мониторинга температуры", "PostgreSQL", "Хранит данные мониторинга температуры")
    Container(CameraSensor, "Камера наблюдения", "Go", "Обрабатвает данные с камеры наблюдения")
    ContainerDb(CameraSensorDB, "База камеры наблюдения", "PostgreSQL", "Хранит данные камеры наблюдения")

    Rel(APIGW, TemprSensor,"Команды получения данных [REST]")
    Rel(APIGW, CameraSensor,"Чтение/запись данных Мониторинг температуры")
    Rel(TemprSensor, TemprSensorDB,"Команды получения данных [REST]")
    Rel(CameraSensor, CameraSensorDB,"Чтение/запись данных Камера наблюдения")
  }

  Boundary(ControlDomain, "Домен управление устройствами") {
 
    Container(WarmСontroller, "Выключатель отопления", "Go", "Управляет состоянием отопления")
    ContainerDb(WarmСontrollerDB, "База управления отоплением", "PostgreSQL", "Конфигурационные и исторические данные управления отоплением")

    Rel(WarmСontroller, WarmСontrollerDB,"Чтение конфигурационных и исторических данные управления отоплением")
    Rel(APIGW, WarmСontroller,"Команды управления [REST]")
    
    Container(GateСontroller, "Открывание воротя", "Go", "Управляет открыванием и закрываеним ворот")
    ContainerDb(GateСontrollerDB, "База управления воротами", "PostgreSQL", "Конфигурационные и исторические данные управления воротами")

    Rel(GateСontroller, GateСontrollerDB,"Чтение конфигурационных и исторических данные управления воротами")
    Rel(APIGW, GateСontroller,"Команды управления [REST]")

    Container(LigthСontroller, "Управление светом", "Go", "Управляет включением и выключением света")
    ContainerDb(LigthСontrollerDB, "База управления светом", "PostgreSQL", "Конфигурационные и исторические данные управления светом")

    Rel(LigthСontroller, LigthСontrollerDB,"Чтение конфигурационных и исторических данные управления светом")
    Rel(APIGW, LigthСontroller,"Команды управления [REST]")
  }
  
  ContainerQueue(RabbitMQ, "RabbitMQ [MQTT] Message Brocker", "Взаимодействие с устройствами по стандартным протоколам[MQTT]")
   Rel(RabbitMQ, APIGW , "Запросы данных и команды управления устройствами[MQTT]")
   Rel(WarmСontroller, RabbitMQ,"Команды управления [MQTT]")
   Rel(GateСontroller, RabbitMQ,"Команды управления [MQTT]")
   Rel(LigthСontroller, RabbitMQ,"Команды управления [MQTT]")
   Rel(TemprSensor, RabbitMQ,"Команды получения данных [MQTT]")
   Rel(CameraSensor, RabbitMQ,"Команды получения данных [MQTT]")
   
  Boundary( Telemetry, "Телеметрия"){
    Container(Grafana, "Grafana", "Grafana", "Построение графиков и отчётова")
    Container(Prometeus, "Prometeus", "Prometeus", "Сбор метрик и телеметрии")
    ContainerDb(PrometeusDatabase, "База сбора логов и телеметрии", "ClickHouse", "Хранит логи и данные телеметрии")

    Rel(administrator, Grafana,"Анализ метрик и телеметрии")
    Rel(Grafana,Prometeus,"Чтение данных для графиков и диаграммам")
    Rel(Prometeus,PrometeusDatabase,"Чтение/Запись данных телеметрии")
  }
}

Boundary( home, "Подключенный дом"){
  System_Ext(ext_WarmSensor, "Датчик температуры подключённого дома", "Передаёт по запросу данные температуры")
  System_Ext(ext_CameraSensor, "Камера наблюдения", "Передаёт по запрос снимки камеры наблюдения подключённого дома")
  System_Ext(ext_Warmcontroller, "Выключатель отопления", "Включает/выключает отопление")
  System_Ext(ext_LigthContorller, "Выключатель света", "Включает/выключает свет")
  System_Ext(ext_GateController, "Система открывания ворот", "Открывает и закрывает ворота")
  Rel(ext_WarmSensor,APIGW,"Управление умным домом[MQTT]")
  Rel(ext_CameraSensor,APIGW,"Управление умным домом[MQTT]")
  Rel(ext_Warmcontroller,APIGW,"Управление умным домом[MQTT]")
  Rel(ext_LigthContorller,APIGW,"Управление умным домом[MQTT]")
  Rel(ext_GateController,APIGW,"Управление умным домом[MQTT]")
 } 

 System_Ext(ext_FireWall, "FireWall на границе умного дома", "Фильтрация входящего/исходящего трафика")
 Rel(administrator,ext_FireWall,"Управление сетевой безопасностью умного домом")
 Rel(ext_FireWall,WarmHouseSystem, "")

 Rel(WebApp, APIGW,"API вызовы [https]")

@enduml
