@startuml
title WormHome Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь просматривает температуру и управляет отоплением")
Person(engineer, "Инженер", "Подключает дома к приложению")
System(WormHomeService, "Управление отоплением", "Управление отоплением, мониторинг температуры, регистрация датчиков ")

System_Ext(home, "Подключенный дом", "Предоставляет температуру, управляет состоянием отопления")
System_Ext(newhome, "Подключаемый дом", "Регистрирует датчик")


Rel(user, WormHomeService, "просмотр температуры и управление отоплением")
Rel(engineer,newhome,"Подключение датчиков дома")
Rel(WormHomeService,home,"включение/выключение отопления")
Rel(WormHomeService,home,"получение температуры")
Rel(newhome, WormHomeService,"регистрация датчика")

@enduml